### Register
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
  "fullName": "Test 7",
  "username": "test_a",
  "email": "test7@mail.com",
  "password": "1234"
  
}

### Login
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "email": "test7@mail.com",
  "password": "1234"
}

### Me (cookie must be sent by client; Postman: enable cookie jar)
GET http://localhost:5000/api/users/me


### Me unified
GET http://localhost:5000/api/users/me/profile

### Membership summary
GET http://localhost:5000/api/users/me/summary

### Logout
POST http://localhost:5000/api/users/logout